var teamDemo = [
	{
	"teamName":"Arizona Diamondbacks",
	// "label":"MLB Players EXAMPLE",
	"white": 68,
	"black": 18,
	"latino": 14,
	"asian": 0,
	"other": 0,
	},
	{
	"teamName":"Atlanta Braves",
	// "label":"MLB Players EXAMPLE",
	"white": 50,
	"black": 20,
	"latino": 20,
	"asian": 5,
	"other": 5,
	},

	{
	"teamName":"Baltimore Orioles",
	// "label":"MLB Players EXAMPLE",
	"white": 45,
	"black": 25,
	"latino": 20,
	"asian": 8,
	"other": 2,
	},
	{
	"teamName":"Boston Red Sox",
	// "label":"MLB Players EXAMPLE",
	"white": 60,
	"black": 5,
	"latino": 25,
	"asian": 5,
	"other": 5,
	},
	{
	"teamName":"Chicago White Sox",
	// "label":"MLB Players EXAMPLE",
	"white": 55,
	"black": 10,
	"latino": 15,
	"asian": 10,
	"other": 10,
	},
	{
	"teamName":"Chicago Cubs",
	// "label":"MLB Players EXAMPLE",
	"white": 60,
	"black": 30,
	"latino": 10,
	"asian": 0,
	"other": 0,
	},
	{
	"teamName":"Cincinnati Reds",
	// "label":"MLB Players EXAMPLE",
	"white": 35,
	"black": 30,
	"latino": 15,
	"asian": 15,
	"other": 5,
	},
	{
	"teamName":"Cleveland Indians",
	// "label":"MLB Players EXAMPLE",
	"white": 55,
	"black": 15,
	"latino": 20,
	"asian": 5,
	"other": 5,
	},
	{
	"teamName":"Colorado Rockies",
	// "label":"MLB Players EXAMPLE",
	"white": 53,
	"black": 25,
	"latino": 15,
	"asian": 5,
	"other": 2,
	},
	{
	"teamName":"Detroit Tigers",
	// "label":"MLB Players EXAMPLE",
	"white": 63,
	"black": 20,
	"latino": 10,
	"asian": 7,
	"other": 0,
	},
	{
	"teamName":"Houston Astros",
	// "label":"MLB Players EXAMPLE",
	"white": 47,
	"black": 13,
	"latino": 33,
	"asian": 5,
	"other": 2,
	},
	{
	"teamName":"Kansas City Royals",
	// "label":"MLB Players EXAMPLE",
	"white": 50,
	"black": 20,
	"latino": 20,
	"asian": 5,
	"other": 5,
	},
	{
	"teamName":"Los Angeles Angels",
	// "label":"MLB Players EXAMPLE",
	"white": 50,
	"black": 25,
	"latino": 25,
	"asian": 0,
	"other": 0,
	},
	{
	"teamName":"Los Angeles Dodgers",
	// "label":"MLB Players EXAMPLE",
	"white": 70,
	"black": 15,
	"latino": 5,
	"asian": 5,
	"other": 5,
	},
	{
	"teamName":"Miami Marlins",
	// "label":"MLB Players EXAMPLE",
	"white": 33,
	"black": 27,
	"latino": 25,
	"asian": 10,
	"other": 5,
	},
	{
	"teamName":"Milwaukee Brewers",
	// "label":"MLB Players EXAMPLE",
	"white": 40,
	"black": 18,
	"latino": 32,
	"asian": 5,
	"other": 5,
	},
	{
	"teamName":"Minnesota Twins",
	// "label":"MLB Players EXAMPLE",
	"white": 55,
	"black": 15,
	"latino": 20,
	"asian": 8,
	"other": 2,
	},
	{
	"teamName":"New York Yankees",
	// "label":"MLB Players EXAMPLE",
	"white": 40,
	"black": 20,
	"latino": 30,
	"asian": 7,
	"other": 3,
	},
	{
	"teamName":"New York Mets",
	// "label":"MLB Players EXAMPLE",
	"white": 50,
	"black": 10,
	"latino": 30,
	"asian": 7,
	"other": 3,
	},
	{
	"teamName":"Oakland Athletics",
	// "label":"MLB Players EXAMPLE",
	"white": 60,
	"black": 10,
	"latino": 20,
	"asian": 9,
	"other": 1,
	},
	{
	"teamName":"Philadelphia Phillies",
	// "label":"MLB Players EXAMPLE",
	"white": 40,
	"black": 15,
	"latino": 25,
	"asian": 15,
	"other": 5,
	},
	{
	"teamName":"Pittsburgh Pirates",
	// "label":"MLB Players EXAMPLE",
	"white": 50,
	"black": 25,
	"latino": 15,
	"asian": 6,
	"other": 4,
	},
	{
	"teamName":"San Diego Padres",
	// "label":"MLB Players EXAMPLE",
	"white": 53,
	"black": 24,
	"latino": 11,
	"asian": 9,
	"other": 3,
	},
	{
	"teamName":"San Fransisco Giants",
	// "label":"MLB Players EXAMPLE",
	"white": 49,
	"black": 21,
	"latino": 20,
	"asian": 1,
	"other": 9,
	},
	{
	"teamName":"Seattle Mariners",
	// "label":"MLB Players EXAMPLE",
	"white": 53,
	"black": 19,
	"latino": 21,
	"asian": 4,
	"other": 3,
	},
	{
	"teamName":"St. Louis Cardinals",
	// "label":"MLB Players EXAMPLE",
	"white": 46,
	"black": 14,
	"latino": 23,
	"asian": 10,
	"other": 7,
	},
	{
	"teamName":"Tampa Bay Rays",
	// "label":"MLB Players EXAMPLE",
	"white": 55,
	"black": 15,
	"latino": 20,
	"asian": 0,
	"other": 10,
	},
	{
	"teamName":"Texas Rangers",
	// "label":"MLB Players EXAMPLE",
	"white": 47,
	"black": 12,
	"latino": 33,
	"asian": 4,
	"other": 4,
	},
	{
	"teamName":"Toronto Blue Jays",
	// "label":"MLB Players EXAMPLE",
	"white": 29,
	"black": 21,
	"latino": 29,
	"asian": 11,
	"other": 10,
	},
	{
	"teamName":"Washington Nationals",
	// "label":"MLB Players EXAMPLE",
	"white": 55,
	"black": 15,
	"latino": 29,
	"asian": 1,
	"other": 0,
	},
]













